# Generated by Django 6.0.5 on 2026-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('STRENGTH', '🏋️ Strength Training'), ('CARDIO', '🏃 Cardio'), ('YOGA', '🧘 Yoga'), ('HIIT', '⚡ HIIT'), ('NUTRITION', '🥗 Nutrition'), ('REHAB', '💪 Rehabilitation'), ('BOXING', '🥊 Boxing'), ('PILATES', '✨ Pilates')], max_length=20)),
                ('experience_years', models.IntegerField()),
                ('bio', models.TextField()),
                ('qualification', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
