# Generated by Django 5.2.5 on 2026-05-14 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_assigned_trainer_and_more'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='schedule_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('STRENGTH', 'Strength Training'), ('CARDIO', 'Cardio'), ('YOGA', 'Yoga'), ('HIIT', 'HIIT'), ('NUTRITION', 'Nutrition'), ('REHAB', 'Rehabilitation'), ('BOXING', 'Boxing'), ('PILATES', 'Pilates')], max_length=20),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('calories_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_goal', models.CharField(blank=True, max_length=100)),
                ('meal_plan', models.TextField(help_text='Breakfast, lunch, dinner, snacks, and hydration guidance')),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.memberprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('weekly_schedule', models.TextField(help_text='Describe the weekly workout split and exercises')),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='accounts.memberprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
