# Generated by Django 6.0.5 on 2026-05-12 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=10)),
                ('attended', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('YOGA', '🧘 Yoga'), ('ZUMBA', '💃 Zumba'), ('CROSSFIT', '🏋️ CrossFit'), ('BOXING', '🥊 Boxing'), ('SPINNING', '🚴 Spinning'), ('PILATES', '✨ Pilates'), ('AEROBICS', '🤸 Aerobics'), ('MEDITATION', '🧠 Meditation')], max_length=20)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('current_bookings', models.IntegerField(default=0)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('equipment_needed', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='booked_classes', through='classes.ClassBooking', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='trainers.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='classbooking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.gymclass'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('member', 'gym_class', 'booking_date')},
        ),
    ]
