# Generated by Django 6.0.5 on 2026-05-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together=set(),
        ),
    ]
