# Generated by Django 5.2.5 on 2026-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classbooking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='class_type',
            field=models.CharField(choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('CROSSFIT', 'CrossFit'), ('BOXING', 'Boxing'), ('SPINNING', 'Spinning'), ('PILATES', 'Pilates'), ('AEROBICS', 'Aerobics'), ('MEDITATION', 'Meditation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
