# Generated by Django 5.2.5 on 2026-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10),
        ),
    ]
