# Generated by Django 5.2.5 on 2026-05-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile_is_vendor_memberprofile_role'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_member_profiles', to='trainers.trainer'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TRAINER', 'Trainer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10),
        ),
    ]
