# Generated by Django 6.0.5 on 2026-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login OTP')], default='REGISTER', max_length=20),
        ),
    ]
