# Generated by Django 6.0.5 on 2026-05-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(choices=[('MONTHLY', 'Monthly (30 days)'), ('QUARTERLY', 'Quarterly (90 days)'), ('HALF_YEARLY', 'Half Yearly (180 days)'), ('YEARLY', 'Yearly (365 days)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('features', models.TextField(help_text='Comma separated features')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MembershipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_plan', models.CharField(max_length=10)),
                ('new_plan', models.CharField(max_length=10)),
                ('upgrade_date', models.DateTimeField(auto_now_add=True)),
                ('additional_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='accounts.memberprofile')),
            ],
        ),
    ]
